import os

folders_to_check = ["/System/Applications", "/System/Applications/Utilities"]
report_filename = "My_Mac_Apps.md"

# 1. Start the report content
report_content = "#  My Mac Software Report\n"
report_content += "This file was automatically generated by my Python script!\n\n"

print("🔍 Scanning Mac apps...")

for folder in folders_to_check:
    report_content += f"## 📂 Apps in {folder}\n"
    try:
        apps = sorted(os.listdir(folder))
        for app in apps:
            if app.endswith(".app"):
                clean_name = app.replace(".app", "")
                # Add to our report string
                report_content += f"- [ ] {clean_name}\n"
    except Exception as e:
        report_content += f"Error reading folder: {e}\n"

# 2. The "Automation" magic: Write the string to a physical file
with open(report_filename, "w") as f:
    f.write(report_content)

print(f"✅ Success! Report saved to: {report_filename}")
